In [2]:
import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Using TensorFlow backend.


#### Import data & divide
- **X** = feature variables
- **y** = output

In [28]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [29]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

#### Encode Catergorical Data
- one-hot encoding must be used for multi-class categorical data
- in this case, **Geography** at index 1 must one-hot enocded
- after the encoding, one dummy variable is removed to avoid falling into the "Dummy Variable trap" 

In [71]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Feature - Geography
label_encoder_1 = LabelEncoder()
X[:, 1] = label_encoder_1.fit_transform( X[:, 1] )

# Feature - Gender
label_encoder_2 = LabelEncoder()
X[:, 2] = label_encoder_1.fit_transform( X[:, 2] )

one_hot = OneHotEncoder( categorical_features=[1] )
X = one_hot.fit_transform(X).toarray()

pd.DataFrame(X) # Note columns 0, 1, 2 - Three dummy variables for feature "Geography"

0    1    2    3    4      5    6     7     8          9    10   11  \
0     0.0  1.0  0.0  1.0  0.0  228.0  0.0  42.0   2.0       0.00  1.0  1.0   
1     0.0  1.0  0.0  1.0  1.0  217.0  0.0  41.0   1.0   83807.86  1.0  0.0   
2     0.0  1.0  0.0  1.0  0.0  111.0  0.0  42.0   8.0  159660.80  3.0  1.0   
3     0.0  1.0  0.0  1.0  0.0  308.0  0.0  39.0   1.0       0.00  2.0  0.0   
4     0.0  1.0  0.0  1.0  1.0  459.0  0.0  43.0   2.0  125510.82  1.0  1.0   
5     0.0  1.0  0.0  1.0  1.0  254.0  1.0  44.0   8.0  113755.78  2.0  1.0   
6     0.0  1.0  0.0  1.0  0.0  431.0  1.0  50.0   7.0       0.00  2.0  1.0   
7     1.0  0.0  1.0  0.0  0.0    8.0  0.0  29.0   4.0  115046.74  4.0  1.0   
8     0.0  1.0  0.0  1.0  0.0  110.0  1.0  44.0   4.0  142051.07  2.0  0.0   
9     0.0  1.0  0.0  1.0  0.0  293.0  1.0  27.0   2.0  134603.88  1.0  1.0   
10    0.0  1.0  0.0  1.0  0.0  137.0  1.0  31.0   6.0  102016.72  2.0  0.0   
11    0.0  1.0  0.0  1.0  1.0  106.0  1.0  24.0   3.0       0.00  2.0  1.0   
12    0.0  1.0  0.0  1.0  0.0   85.0  0.0  34.0  10.0       0.00  2.0  1.0   
13    0.0  1.0  0.0  1.0  0.0  158.0  0.0  25.0   5.0       0.00  2.0  0.0   
14    0.0  1.0  0.0  1.0  1.0  244.0  0.0  35.0   7.0       0.00  2.0  1.0   
15    1.0  0.0  1.0  0.0  0.0  225.0  1.0  45.0   3.0  143129.41  2.0  0.0   
16    1.0  0.0  1.0  0.0  0.0  262.0  1.0  58.0   1.0  132602.88  1.0  1.0   
17    0.0  1.0  0.0  1.0  1.0  158.0  0.0  24.0   9.0       0.00  2.0  1.0   
18    0.0  1.0  0.0  1.0  1.0  196.0  1.0  45.0   6.0       0.00  1.0  0.0   
19    0.0  1.0  0.0  1.0  0.0  335.0  0.0  24.0   6.0       0.00  2.0  1.0   
20    0.0  1.0  0.0  1.0  0.0  341.0  1.0  41.0   8.0       0.00  2.0  1.0   
21    0.0  1.0  0.0  1.0  1.0  245.0  0.0  32.0   8.0       0.00  2.0  1.0   
22    0.0  1.0  0.0  1.0  1.0  119.0  0.0  38.0   4.0       0.00  1.0  1.0   
23    0.0  1.0  0.0  1.0  0.0  278.0  1.0  46.0   3.0       0.00  2.0  0.0   
24    0.0  1.0  0.0  1.0  0.0  455.0  0.0  38.0   5.0       0.00  1.0  1.0   
25    0.0  1.0  0.0  1.0  0.0  186.0  1.0  25.0   3.0       0.00  2.0  0.0   
26    1.0  0.0  1.0  0.0  0.0  365.0  1.0  36.0   2.0  136815.64  1.0  1.0   
27    0.0  1.0  0.0  1.0  0.0  180.0  1.0  44.0   9.0       0.00  2.0  0.0   
28    1.0  0.0  1.0  0.0  0.0  183.0  0.0  43.0   3.0  141349.43  1.0  1.0   
29    0.0  1.0  0.0  1.0  0.0   20.0  1.0  29.0   0.0   59697.17  2.0  1.0   
...   ...  ...  ...  ...  ...    ...  ...   ...   ...        ...  ...  ...   
9970  0.0  1.0  0.0  1.0  0.0  127.0  1.0  42.0   7.0  151027.05  2.0  1.0   
9971  0.0  1.0  0.0  1.0  0.0  442.0  0.0  34.0   3.0  144751.81  1.0  0.0   
9972  0.0  1.0  0.0  1.0  0.0  367.0  1.0  26.0   4.0  155739.76  1.0  1.0   
9973  0.0  1.0  0.0  1.0  0.0  220.0  1.0  27.0   7.0       0.00  2.0  1.0   
9974  0.0  1.0  0.0  1.0  0.0  192.0  1.0  33.0   7.0  122531.86  1.0  1.0   
9975  1.0  0.0  1.0  0.0  0.0  219.0  1.0  50.0   1.0  113957.01  2.0  1.0   
9976  0.0  1.0  0.0  1.0  0.0  246.0  0.0  33.0   7.0  103377.81  1.0  1.0   
9977  0.0  1.0  0.0  1.0  0.0  292.0  0.0  32.0   9.0       0.00  2.0  1.0   
9978  0.0  1.0  0.0  1.0  0.0  383.0  1.0  40.0   9.0   93017.47  2.0  1.0   
9979  0.0  1.0  0.0  1.0  0.0  286.0  0.0  58.0   1.0   90022.85  1.0  0.0   
9980  0.0  1.0  0.0  1.0  1.0  350.0  1.0  35.0   6.0   74371.49  1.0  0.0   
9981  1.0  0.0  1.0  0.0  0.0  107.0  1.0  42.0   3.0  152039.70  1.0  1.0   
9982  1.0  0.0  1.0  0.0  0.0  264.0  0.0  46.0   7.0  137145.12  1.0  1.0   
9983  0.0  1.0  0.0  1.0  0.0  222.0  1.0  40.0   4.0       0.00  1.0  0.0   
9984  1.0  0.0  1.0  0.0  0.0  211.0  1.0  35.0   7.0   90602.42  2.0  1.0   
9985  0.0  1.0  0.0  1.0  0.0  268.0  1.0  36.0   6.0  123841.49  2.0  1.0   
9986  1.0  0.0  1.0  0.0  0.0  282.0  1.0  47.0   1.0  183579.54  2.0  0.0   
9987  0.0  1.0  0.0  1.0  1.0  215.0  1.0  30.0   8.0  180307.73  2.0  1.0   
9988  0.0  1.0  0.0  1.0  0.0  384.0  1.0  30.0   4.0       0.00  2.0  1.0   
9989  0.0  1.0  0.0  1.0  1.0

In [72]:
# Remove one dummy variable
X = X[:, 1:]
pd.DataFrame(X) # Note index 0, 1 

0    1    2    3      4    5     6     7          8    9    10   11  \
0     1.0  0.0  1.0  0.0  228.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     1.0  0.0  1.0  1.0  217.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  1.0  0.0  111.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  1.0  0.0  308.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     1.0  0.0  1.0  1.0  459.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
5     1.0  0.0  1.0  1.0  254.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0   
6     1.0  0.0  1.0  0.0  431.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   
7     0.0  1.0  0.0  0.0    8.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0   
8     1.0  0.0  1.0  0.0  110.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   
9     1.0  0.0  1.0  0.0  293.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   
10    1.0  0.0  1.0  0.0  137.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   
11    1.0  0.0  1.0  1.0  106.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   
12    1.0  0.0  1.0  0.0   85.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   
13    1.0  0.0  1.0  0.0  158.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0   
14    1.0  0.0  1.0  1.0  244.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   
15    0.0  1.0  0.0  0.0  225.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   
16    0.0  1.0  0.0  0.0  262.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0   
17    1.0  0.0  1.0  1.0  158.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   
18    1.0  0.0  1.0  1.0  196.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0   
19    1.0  0.0  1.0  0.0  335.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   
20    1.0  0.0  1.0  0.0  341.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0   
21    1.0  0.0  1.0  1.0  245.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0   
22    1.0  0.0  1.0  1.0  119.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0   
23    1.0  0.0  1.0  0.0  278.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0   
24    1.0  0.0  1.0  0.0  455.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0   
25    1.0  0.0  1.0  0.0  186.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0   
26    0.0  1.0  0.0  0.0  365.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0   
27    1.0  0.0  1.0  0.0  180.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   
28    0.0  1.0  0.0  0.0  183.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0   
29    1.0  0.0  1.0  0.0   20.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   
...   ...  ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9970  1.0  0.0  1.0  0.0  127.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0   
9971  1.0  0.0  1.0  0.0  442.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0   
9972  1.0  0.0  1.0  0.0  367.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0   
9973  1.0  0.0  1.0  0.0  220.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0   
9974  1.0  0.0  1.0  0.0  192.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   
9975  0.0  1.0  0.0  0.0  219.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0   
9976  1.0  0.0  1.0  0.0  246.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   
9977  1.0  0.0  1.0  0.0  292.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   
9978  1.0  0.0  1.0  0.0  383.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0   
9979  1.0  0.0  1.0  0.0  286.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0   
9980  1.0  0.0  1.0  1.0  350.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   
9981  0.0  1.0  0.0  0.0  107.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   
9982  0.0  1.0  0.0  0.0  264.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0   
9983  1.0  0.0  1.0  0.0  222.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0   
9984  0.0  1.0  0.0  0.0  211.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   
9985  1.0  0.0  1.0  0.0  268.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   
9986  0.0  1.0  0.0  0.0  282.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   
9987  1.0  0.0  1.0  1.0  215.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0   
9988  1.0  0.0  1.0  0.0  384.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   
9989  1.0  0.0  1.0  1.0  450

#### Split into training and test set
- 80% : 20 %

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
list(map(len, (X_train, X_test, y_train, y_test )))

#### Feature Scaling

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_train)

Values before **standard scaling**

In [68]:
X_train

array([ 0.5698444 , -0.5698444 ,  0.5698444 ,  1.74309049,  0.1692298 ,
       -1.09168714, -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,
        0.64259497, -1.03227043,  1.10643166])

Values after **standard scaling**

In [43]:
X_train

array([[-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -1.75486502, -1.75486502, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  0.5698444 ,  0.5698444 , ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -1.75486502, -1.75486502, ...,  0.64259497,
        -1.03227043,  0.32472465]])

#### The Sequential() model keeps all layers in track

In [56]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()

## Adding dense layers to our model

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
`activation` is the element-wise activation function
`kernel` is a weights matrix 
`bias` is a bias vector (only applicable if `use_bias` is `True`).

Note: if the input to the layer has a rank greater than 2, then
it is flattened prior to the initial dot product with `kernel`.

#### Example


    # as first layer in a sequential model:
    model = Sequential()
    model.add(Dense(32, input_shape=(16,)))
    # now the model will take as input arrays of shape (*, 16)
    # and output arrays of shape (*, 32)

    # after the first layer, you don't need to specify
    # the size of the input anymore:
    model.add(Dense(32))

#### Params
    input_shape : dim of inputs, MUST be list
    units: dimensionality of the output
    activation: Activation function to use, MUST be specified
    kernel_initializer: 'uniform'
    kernel_regularizer: Regularizer function applied to
    bias_regularizer: Regularizer function applied to the bias vector
    

In [57]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_shape = [11]))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

Compiling the model with:
- Optimizer: Adam optimizer 
- Loss function: binary cross entropy (as our output variable is binary)
- Metrics: accuracy (legacay metrics recall, precision cease to exist)

In [58]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the model with both training sets

In [59]:
classifier.fit(x = X_train, y = y_train, batch_size = 10, epochs = 100)

ValueError: Error when checking input: expected dense_8_input to have shape (None, 11) but got array with shape (8000, 13)

In [62]:
len(X_train)

13

In [146]:
y_pred = classifier.predict(X_test)

Notice all the output are probabilities from our sigmod funciton

In [147]:
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

We threshold all the values at 0.5

In [148]:
y_pred = y_pred > 0.5
y_pred 

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [151]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


#### Predicitng from a single obeservation
- input must be [ [] ], as all inputs are 2D matrices
- must be scaled identically to the training data

In [163]:
to_predict = np.array([ [0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000] ])
to_predict = sc.fit_transform(to_predict) # Scaling
    

c:\nlp\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [1]:
classifier.predict( x = to_predict)

NameError: name 'classifier' is not defined

In [ ]:
new_prediction = classifier.predict( x = np.array())